# wget https://raw.githubusercontent.com/grafana/loki/v2.3.0/production/docker-compose.yaml
# wget https://raw.githubusercontent.com/grafana/loki/v2.3.0/cmd/loki/loki-local-config.yaml

version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.3.0
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - "./config/loki/loki-local-config.yaml:/etc/loki/local-config.yaml:ro"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:8.1.1
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "./config/grafana/provisioning:/etc/grafana/provisioning:ro"
    environment:
    - "GF_SECURITY_ADMIN_PASSWORD=CHANGEME"
    - "GF_AUTH_ANONYMOUS_ENABLED=true"
    networks:
      - loki 
